`timescale 1ns / 1ps

module tb_full_adder;
    logic a, b, cin, sum, cout;

    // File reading variables
    int fd;
    int exp_a, exp_b, exp_cin, exp_sum, exp_cout;
    int mismatches = 0;

    // Instantiate the Unit Under Test (UUT)
    full_adder_opt uut (
        .a(a), .b(b), .cin(cin),
        .sum(sum), .cout(cout)
    );

    initial begin
        // Open the golden file generated by C model
        fd = $fopen("expected_outputs.txt", "r");
        if (fd == 0) begin
            $display("Error: Could not open expected_outputs.txt");
            $finish;
        end

        $display("Time\ta\tb\tcin\t|\tsum\tcout\t|\tExpected S\tExpected Cout\tMatch?");
        $display("-----------------------------------------------------------------------------------------");

        // Read line by line format: "%d %d %d %d %d"
        while (!$feof(fd)) begin
            if ($fscanf(fd, "%d %d %d %d %d\n", exp_a, exp_b, exp_cin, exp_sum, exp_cout) == 5) begin
                // Apply stimulus
                a = exp_a;
                b = exp_b;
                cin = exp_cin;
                #10; // Wait for combinational logic

                // Check outputs
                if (sum != exp_sum || cout != exp_cout) begin
                    $display("%0t\t%b\t%b\t%b\t|\t%b\t%b\t|\t%b\t\t%b\t\tFAIL", $time, a, b, cin, sum, cout, exp_sum, exp_cout);
                    mismatches++;
                end else begin
                    $display("%0t\t%b\t%b\t%b\t|\t%b\t%b\t|\t%b\t\t%b\t\tPASS", $time, a, b, cin, sum, cout, exp_sum, exp_cout);
                end
            end
        end

        $fclose(fd);
        $display("-----------------------------------------------------------------------------------------");

        if (mismatches == 0)
            $display("SUCCESS: Verrified all combinations against C golden model.");
        else
            $display("FAILURE: %0d mismatches found.", mismatches);

        $finish;
    end
endmodule
